version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    container_name: postgres-cardb
    image: postgres
    environment:
      POSTGRES_DB: cardb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    restart: unless-stopped

  backend:
    build: .
    container_name: cars_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cardb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    restart: always

networks:
  db:
    driver: bridge

volumes:
  db: