name: JUnit-Tests
on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 4.0.0

      - name: All the Tests and Coverage check
        run: mvn clean install